/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentManager from "@strapi/content-manager/strapi-admin";
import email from "@strapi/email/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "content-manager": contentManager,
    email: email,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
  },
});
